language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

env:
  matrix:
    - COMPOSER_PACKAGES='symfony/console=^2.0 symfony/event-dispatcher=^2.0 symfony/monolog-bridge=^2.0'
    - COMPOSER_PACKAGES='symfony/console=^3.0 symfony/event-dispatcher=^3.0 symfony/monolog-bridge=^3.0'
    - COMPOSER_PACKAGES='symfony/console=^4.0 symfony/event-dispatcher=^4.0 symfony/monolog-bridge=^4.0'
    - COMPOSER_PACKAGES='symfony/console=^5.0 symfony/event-dispatcher=^5.0 symfony/monolog-bridge=^5.0'

matrix:
  exclude:
    - php: 5.6
      env: COMPOSER_PACKAGES='symfony/console=^4.0 symfony/event-dispatcher=^4.0 symfony/monolog-bridge=^4.0'
    - php: 7.0
      env: COMPOSER_PACKAGES='symfony/console=^4.0 symfony/event-dispatcher=^4.0 symfony/monolog-bridge=^4.0'

install:
  - composer require $COMPOSER_PACKAGES
  - composer install

before_script:
  - mysql -u root -e 'create database lhm_php_test;'

script:
  - vendor/bin/phpunit

sudo: false
